### ISSUE TITLE
In Three draw can turtles change color or are they fixed when first drawn?

### ISSUE THREAD

**Issue by stigmergic** [backspaces/agentscript#20] opened 2021-01-29 22:38 UTC

**Comment by backspaces** [comment] 2021-02-01 18:43
Just checked: In ThreeMeshes.js:
- Colors can be changed on all the 2D turtle "sprites" (i.e. images on a quad mesh)
- Ditto for Points
- But not for Obj3DMesh turtles which are one mesh per turtle rather than a span within a BufferGeometry add it does not manage update the color. 

I suspect that's what you're using, a shape that is real 3D. 

Let me check on just how easy that would be to add color changes for the mesh-per-turtle

**Comment by backspaces** [comment] 2021-02-01 20:54
OK, here's a fairly easy (I think!) approach. Each draw checks the requested shape,size,color (the viewFcn(turtle)) with the existing one. If any differ, simply delete the existing mesh and create an entirely new one. Would that solve the issue?

**Comment by stigmergic** [comment] 2021-02-01 21:46
Yes I expect it would.  I think it is important that turtles be able to change color.  I also understand that it could have an impact on performance.  But I tend toward first being able to do it,  and later if necessary worrying about speeding it up.

**Comment by backspaces** [comment] 2021-02-03 01:07
OK, I've made it possible to modify the shape, color, size of an existing mesh. 
BUT it requires colors to be typed colors.

Basically the problem is that the ctor does a lot of preprocessing of the drawOptions, so simply changing the drawOptions can bypass that preprocessing.

The best solution would be to add a method for changing the entire drawOptions object but I think this may do for now.

**Comment by stigmergic** [comment] 2021-02-03 16:33
seeing it run a little slowly.
Here are my drawOptions

```const drawOptions = {
    turtlesShape: (t) => (isCamera(t) ? 'Dart' : 'Sphere'),
    turtlesColor: (t) =>
        t.el < 0
            ? 'black'
            : isPlanet(t)
            ? planetColor(t.data.name)
            : isStar(t)
            ? 'yellow'
            : 'red',
    turtlesSize: (t) =>
        isPlanet(t) ? (t.data.name == 'Sun' ? 3 : 1.5) : isStar(t) ? 0.3 : 4,
}```

**Comment by backspaces** [comment] 2021-02-09 23:06
@stigmergic I think this is fixed now. I'll close it for now and hope it's fixed :)

**Closed as completed by backspaces** 2021-02-09 23:06 UTC
