### ISSUE TITLE
flock model wiggle regression

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#41] opened 2021-04-24 19:03 UTC
Here's a pebble showing the boid wiggle behavior that I think is a regression:

![FlockModel 2021-04-24T18_39_13 124Z](https://user-images.githubusercontent.com/704368/115969777-95abbb00-a4f3-11eb-89b9-bbdfa9a91a4c.png)

You should be able to download that image, then drag it over to https://gentleplants.com/as/editor/ (testing this pebble mechanism at the same time :-P)

If you watch a single boid, you'll see that instead of flying smoothly, it has a very small oscillation back and forth around its heading.

**Comment by stephenguerin** [comment] 2021-04-26 10:08
the "wiggle" is coming from the align force with nearby boids. Here's a pebble with just one boid that shows no wiggle.

![FlockModel_oneBoid-2021-04-26T09_55_31 725Z](https://user-images.githubusercontent.com/1078567/116065916-b9324b00-a644-11eb-8562-13173705a78f.png)

And here's a second pebble with 40 boids but choosing flockmates based on inCone instead of inRadius. Note the "leaders" don't wiggle but the "followers" do
![FlockModel 2021-04-26T10_03_32 407Z](https://user-images.githubusercontent.com/1078567/116066192-031b3100-a645-11eb-804e-9f6801c2820a.png)

**Comment by backspaces** [comment] 2021-04-26 15:28
Love the ide & pebbles! I gotta see how the drag/drop works.

Re: wobbling regression to flock:
I just committed and published flock as a mvc.

> https://agentscript.org/mvc/flock.html

To check for wobble:
* start the model
* fps low, 10 say
* population 100
* turtleSize 2 or three
(if model stops at 500, hit toggle to continue)

I think the wobbling is “normal” .. i.e. adjustments to create flocking.  It is more obvious due to larger turtles? Lower population and fps? But the turtles that are solo don’t wobble.

What do you think? We could grab an earlier version and hand edit it to see if it is steadier.

BTW: I'm thinking of changing the FlockModel default to be 100 population rather than 1000 .. it shows flock clusters so nicely.

**Comment by bennlich** [comment] 2021-04-26 17:32
Here's a pebble that uses AS 0.8.3 (pulled in via skypack):

![FlockModel 0 8 3 2021-04-26T17_19_27 145Z](https://user-images.githubusercontent.com/704368/116125412-4fcd2f00-a67a-11eb-9d4e-3fcf2892b2e9.png)

I added the version tag to the imports at the top to get an earlier version, and adjusted the model code to match what was in the repo.

The motion is definitely a little different. There's still wiggle, but it's different wiggle. Less anxious :-P

I'm not sure it matters enough to chase it down. Going to close this for now. Thanks y'all.

**Comment by stephenguerin** [comment] 2021-04-26 18:09
Thanksm Benny for testing with a previous version. It's so convenient to run these pebbles! And I like that you were able to bring in the old version of AS (which could be a pebble reference in the future). Let's keep this issue open as I think there's more clumping happening in the newer AS version (Owen, can you add me as a collaborator so I can do things like re-opening issues)

![image](https://user-images.githubusercontent.com/1078567/116129885-d76d6a80-a687-11eb-9aa8-ce36b90d2f44.png)

**Comment by stephenguerin** [comment] 2021-04-26 19:11
I suspect it's somewhere in the cohere and the methods it's calling....

**Comment by backspaces** [comment] 2021-05-21 14:56
Is this still an issue? I'm closing for now, feel free to reopen if I'm mistaken.

**Closed as completed by backspaces** 2021-05-21 14:56 UTC
