### ISSUE TITLE
What's up with Agents.inCone and Agents.inRadius?

### ISSUE THREAD

**Issue by bennlich** [backspaces/agentscript#87] opened 2015-03-20 05:41 UTC
See [here](https://github.com/backspaces/agentscript/blob/298be4a0a4a1844b8f825c8d9f8d952e7e5e6129/src/agents.coffee#L48-L58).

Why do both functions calculate the unused set `as`?

Also, the call to `inRect()` results in a bug when doing `someAgent.inCone(someTurtleSet, ...)`, because `someAgent.inCone()` automatically calls `someTurtleSet.inCone(someAgent.p, ...)`, which in turn calls `someTurtleSet.inRect(someAgent.p, ...)`, which expects an agent, not a patch.

**Comment by backspaces** [comment] 2015-03-20 15:43
Damn.

This all worked a while back, I have a sketch that I think exercises it and
worked during the performance study over a year ago.  Odd that it fails now.

The logic of getting the patch rect, and then extract all the agents within
them is correct but something is definitely wrong with an array calculated
then not used

The commenting out seems to suggest an attempt to refactor agentset to
handle basic forms of inRect and inCone rather keeping it all in agents.
Doesn't make a lot of sense unless patches also have inRect/inCone
functions, don't recall.

I haven't time today to tackle this, my Dropbox is malfunctioning or hacked
so am scrambling to fix it.  I also can't make npm install work. So big sys
admin day, alas.

   -- Owen

**Comment by backspaces** [comment] 2015-03-20 16:06
Ah, I bet this has to do with breeds and asSet returning supersets of
AgentSet.

The commented out lines presumed that "as" is a basic AgentSet, not for
example a Agents AgentSet.

This is pretty fundamental.  I'm not sure how NetLogo handles it when it
returns an agentset from a computation .. i.e. returns all the agents
within a radius of a rect/point.  AgentSet is basically fancy array and its
super classes have some additional capability.

The asSet function semantics, in other words, is the key issue here I
think.  Gotta see what the NL semantics are.

**Comment by bennlich** [comment] 2015-03-22 00:45
Hmm. I don't think I follow. What about the commented lines presumes a basic AgentSet? And wouldn't that presumption be okay? `asSet` should return a basic AgentSet unless an additional argument is passed in, right?

One problem seems to be that the `a` in `Agents.inCone(a, ...)` and `Agents.inRadius(a, ...)` is an arbitrary object (Agent or Patch), while the `a` in `Agents.inRect(a, ...)` is presumed to be an Agent, not a Patch.

Maybe `inRect()` should be moved from `Agents` to `AgentSet`, and written to accept an Agent or a Patch?

**Comment by backspaces** [comment] 2015-03-22 22:41
Here's an image of a cone test sketch that I'll update to deal with agents in radius/cone as well as patches.  Its been a while since I've wrestled with this, its subtle, especially with taurus topology, which I really want to keep.

![google chrome073](https://cloud.githubusercontent.com/assets/124366/6771868/1e53e922-d0b2-11e4-8066-1a173150938a.jpg)

**Comment by bennlich** [comment] 2015-03-23 00:02
Awesome! Lemme know if you wanna hangout about this sometime tomorrow
(Monday).

**Comment by stephenguerin** [comment] 2015-03-23 00:07
>  especially with taurus topology, which I really want to keep.

Taurus topology will come with all kinds of bullshit. Torus is good enough.
:-)

--- -. .   ..-. .. ... ....   - .-- ---   ..-. .. ... ....
Stephen.Guerin@Redfish.com
1600 Lena St #D1, Santa Fe, NM 87505
office: (505) 995-0206  mobile: (505) 577-5828
tw: @redfishgroup  skype: redfishgroup
redfish.com  |  simtable.com

**Comment by bennlich** [comment] 2015-03-23 00:20
rofl

**Comment by backspaces** [comment] 2015-03-23 03:58
Blush! Well, being elder comes with excuses too!  <3 my friends.

**Comment by backspaces** [comment] 2015-03-23 04:25
BTW:  the semantics I was looking for is sorta like this:
    http://ccl.northwestern.edu/netlogo/docs/dictionary.html#turtle-set
Just look at that page, and do a "find" on "agentset" within the browser.

Our asSet() functionality was attempting to be completely general, and
prototypal.

I'll have to make all this work.  Probably the current stunt works, but
with an argument specifying what sort of agentset the returned array is
supposed to be.

A couple of beers should help.

Steve: do you know what we're dealing with?  We want to use an array
comprehension which returns a JS array and turn it into an agentset using
the prototypal stunt of switching the __proto__.

But I think the NL semantics are likely to be more specific.  It is very
useful so we want it.

   -- Owen

**Comment by bennlich** [comment] 2015-03-23 05:13
> Probably the current stunt works, but
with an argument specifying what sort of agentset the returned array is
supposed to be.

Didn't you already implement that [here](https://github.com/backspaces/agentscript/blob/master/src/agentset.coffee#L37)? =D

**Comment by backspaces** [comment] 2015-03-23 15:24
God I'm smart!

Yeah, I did remember asSet had a defaulted set type, although I couldn't
recall if the default was AgentSet or @, i.e. the "current" agentset.

I'm not sure NL had the specific "asTurtles" etc so it was helpful to find
out it too needs that sort of thing.

Gotta go start a dead battery but should be on the air again around noon.
You still in town?

   -- Owen

**Comment by bennlich** [comment] 2015-03-23 16:55
Not in town, but let's do a talky?

**Comment by backspaces** [comment] 2015-03-24 15:50
​It does seem like an odd method loop in inCone & inRadius.  One of the
dangers of "this/@" is that if I use @foo in my method, I've lost control,
sub-classes can implement it and my method has to use the results  ...  at
its peril.  The JS folk have always looked at "super" as an anti-pattern.

I thought asSet() would limit the scope but apparently that's not where the
problem is.  I tried changing agent.inCone/inRadius to use the commented
out asSet'ed arrays yesterday and got a loop.

There are a couple of ways to fix this, I think. One would be to move it to
Util with the rest of the geometry, thus controlling inheritance.

An other would be to study in detail the relation between agents and
patches: agents find the agents inRadius by using patch's patchRect, then
fetching all the agents in that rect (via p.agentsHere​) and then finding
which agents are within a circle/radius.

Another would be to just fix the inheritance, probably by re-naming the
agentSet inSet/inRadius to be used as utilities by agents/patches w/o the
danger of method loops.

Oh, and NL apparently has some problems with this: in-cone is for agents
only, in-radius can be used by agents & patches both.

Sorry to have been unavailable yesterday.  I'll be available after lunch
today I hope.

**Comment by SethTisue** [comment] 2015-03-24 16:22
NetLogo's `in-cone` is turtle-only because it uses the turtle's heading to determine the orientation of the cone. (If the modeler needs some arbitrary cone on the plane, they can temporarily create a turtle with the appropriate location and orientation.)

**Comment by backspaces** [comment] 2015-03-24 18:43
Doh! Why didn't I think of that! As always, thanks!

**Comment by bennlich** [comment] 2015-03-26 06:31
> I thought asSet() would limit the scope but apparently that's not where the
problem is.  I tried changing agent.inCone/inRadius to use the commented
out asSet'ed arrays yesterday and got a loop.

That's weird. It doesn't seem like it would loop. Can you send me your test sketch?

**Comment by backspaces** [comment] 2015-03-26 16:39
On Thu, Mar 26, 2015 at 12:31 AM, Benny Lichtner <notifications@github.com>
wrote:

> I thought asSet() would limit the scope but apparently that's not where the
> problem is. I tried changing agent.inCone/inRadius to use the commented
> out asSet'ed arrays yesterday and got a loop.
>
> That's weird. It doesn't seem like it would loop. Can you send me your
> test sketch?
>
​I committed & updated gh-pages, & luckily have the sketch in it:
​    ​
http://agentscript.org/sketches/cone.html
​It will likely fail in some of the tests (commented out in the source)

​But while doing all this, and exploring the NL semantics, I came across an
interesting hole in my understanding of "derived" agentsets.  If, for
example, I have a breed "cars" and I do an inRadius with it, does the
resulting agentset still have a breed of "cars"?

This is where I stumbled across ​these, NL has a lot of type-testing:

is-agent? is-agentset? is-boolean? is-<breed>? is-command-task?
is-directed-link? is-link? is-link-set? is-list? is-number? is-patch?
is-patch-set? is-reporter-task? is-string? is-turtle? is-turtle-set?
is-undirected-link?


And also found in-radius/in-cone are categorized under AgentSets:
  http://ccl.northwestern.edu/netlogo/docs/dictionary.html#agentsetgroup
.. and that NL also has specific versions of our asSet .. for example:
  http://ccl.northwestern.edu/netlogo/docs/dictionary.html#patch-set
.. and there is NOT a breed-set as far as I can see.

I also noticed that sometime in the past, asSet, which simply sets the
__proto__ of an array, also sets it's "breed".  I'm pretty sure it does it
incorrectly .. it just sets it to be the breed of the first element of the
array.

So I think the semantics of agentsets is playing into how we do inRadius,
inCone, and how we do optimization with patchRect:

patches act as a quadtree, sorta, via Patches.patchRect which is used to
improve performance.  If I have a.inRadius(cars, radius, meToo), I'll first
do a patches.patchRect, and use p.agentsHere to get all the agents in the
rect, then calculate those within radius from me (with correct topology),
finally reporting the car breeds in the agents that are inRadius.  Whew!


Way TMI but I guess it shows just how subtle NL's ecology is! It won't
matter as long as we are consistent, but consistency is quite a challenge
so "stealing NLs" is generally a good idea.

**Comment by SethTisue** [comment] 2015-03-26 18:59
note NetLogo/NetLogo#375 and NetLogo/NetLogo#402 though. our code for this still has some flaws.

**Comment by backspaces** [comment] 2015-03-26 20:58
Superb, thanks!

.. And, luckily, I must be on the right path .. I woke up this morning with
exactly that idea.  Probably as simple as: if agentset.length < radius *
radius (radius being the length of the cone/radius of the circle).

BTW: AgentSets.  Do derived agentsets .. i.e. subsets of an agentset as the
result of a function call .. have the same breed as the full breed set?
I'm assuming yes, I'll read more of the docs (amazing how sophisticated NL
is .. its been too long since I've been intensely using it)

I.e. if I have a "cars" turtle breed, and I get a subset "close-cars" of
"cars" via inRadius, say, my bet is that:

is-agentset? close-cars
is-turtle-set? close-cars

and if it existed (not sure why not)

is-car-set? close-cars

.. would all return true?

JS has a  closeCars.isPrototypeOf(set):

quote: The isPrototypeOf() method tests for an object in another object's
prototype chain.

Thus would return true in the cases above, at least if we set the agentset
proto to be that of cars.

Thanks again, these insights are absolutely invaluable!

   -- Owen

**Comment by SethTisue** [comment] 2015-03-26 21:10
NetLogo knows whether an agentset (even an empty one!) is a turtleset, patchset, or linkset. But it doesn't keep any breed information. So once you do e.g. `cars in-radius 5` or whatever, the resulting agentset is just an ordinary turtleset. There is no `is-car-set?`, and NetLogo doesn't retain the information that would be needed to perform that check in O(1). It would have to check each turtle. I don't think a situation has ever arisen where we thought retaining that information would be advantageous.

**Comment by backspaces** [comment] 2015-03-27 02:50
That's good news, I prefer this simplification.  Love the empty agentset
being able to identify itself!

**Comment by backspaces** [comment] 2015-03-28 16:53
Status on all of this.

1 - Seth's emails certainly pointed out many issues:
    a) Derived agentSets (returned from functions) can be subtle/problematic
        - The set can be "sparse": some may be missing in the patchRect
           Ex: An "even" agentset function, returning every other breed
value in a breed set.
        - This currently would cause "over reporting" using the "bounding"
cached patchRect optimization,
           i.e. returning agents not in the agentset.
        - Managing this can be quite an issue; using a bash-like uniq of the
          concatenation of the agentset and the cached agents works but
isn't cheap
    b) Performance is by no means obvious.  At what size agentset is it
faster
        to just avoid rect optimization and do the computation over all
members of the agentset.
        My guess it is around agentset.length < rect.length (side squared).

2 - This led me to sorta the reverse of cached patches: a function that
returns all of the agentset members in a given patch rect (below).  Took a
bit of time to get it right but its pretty performant and handles torus
well and cheaply.

3 - We can avoid some subtle problems by very clear statements of our
semantics.  Basically, if the agentset is a full breed, then we can rely on
our current patch caching.  And naturally patches themselves are simple,
even though we do allow patch breeds.  If the agentset, however, is derived
from a function that returns an agentset, then we have to be very careful.

I'm thinking inCone and inRadius of full agentsets (turtles, patches etc)
should use a cached rect if available, otherwise compute the patchRect
(below).  All derived agentsets use agentsInRect.  Exception: if set.length
is less than the size of the patch rect, or similar, just do the
computation w/o first reducing to the bounding patch rect.

   -- Owen

# Return an array of agentset items in a rectangle centered on the given
# agent's patch - dx, dy units to the right/left and up/down, integers.
# Exclude agent itself in result unless meToo is true, default false.
agentsInRect: (array, agent, dx, dy, meToo = false) ->
  p = agent.p ? agent # better test needed, isPatch(agent)
  rect = [];
  # Note: we do not "clip" the min/max/X/Y to be within the patches.
  # For non-torus, this is OK: the x,y test is still valid.
  # For torus, it allows us to adjust the x,y to be wrapped appropriately.
  minX = p.x-dx; maxX = p.x+dx
  minY = p.y-dy; maxY = p.y+dy
  # Is the p,dx,dy entirely inside the patches?
  inside = (minX >= @minX) and (maxX <= @maxX) and
           (minY >= @minY) and (maxY <= @maxY)
  for a in array
    # x,y values are patch integer x,y
    if a.p? then x = a.p.x; y = a.p.y else x = a.x; y = a.y
    # Adjust torus x,y if appropriate
    if @isTorus and not inside
      x += @numX if x < minX; x -= @numX if x > maxX
      y += @numY if y < minY; y -= @numY if y > maxY
    # Test x,y inside rect
    if (minX <= x <= maxX and minY <= y <= maxY) and (meToo or agent isnt a)
      rect.push a
  rect

# Return a rectangle of patches centered on p, with dx,dy to the right/left
# of p, integers. Exclude p from results if meToo is false.
# Performance: If the rect is in the pRect cache for this patch, return it.
# See cacheRect()
patchRect: (p, dx, dy, meToo=false) ->
  return p.pRect if p.pRect? and (p.pRect.radius is dx) and (dx is dy)
  rect = []; # REMIND: optimize if no wrapping, rect inside patch boundaries
  for y in [p.y-dy..p.y+dy] by 1 # by 1: perf: avoid bidir JS for loop
    for x in [p.x-dx..p.x+dx] by 1
      if @isTorus or (@minX<=x<=@maxX and @minY<=y<=@maxY)
        if @isTorus
          x+=@numX if x<@minX; x-=@numX if x>@maxX
          y+=@numY if y<@minY; y-=@numY if y>@maxY
        pnext = @patchXY x, y # much faster than coord()
        rect.push pnext if (meToo or p isnt pnext)
  @asSet rect

**Comment by backspaces** [comment] 2015-04-08 02:46
Although this has not gone thru performance optimization yet, I'm closing it.  Been fun and quite illuminating. Can't wait to read the book!

**Closed by backspaces** 2015-04-08 02:46 UTC

**Comment by bennlich** [comment] 2015-04-10 03:43
Looks and sounds good, Owen! Maybe make a PR with these functions so we can comment in-line?

**Comment by bennlich** [comment] 2015-04-10 04:54
Oh, woops. Didn't see you had closed this. Did you already merge it in?

**Comment by backspaces** [comment] 2015-04-10 16:40
Yup.  Some variations of the prior theme.

I'm now in the basement (of the code so to speak) and working on the Chrome
performance regression.  The suspects are animator (rAF) and shapes (just
'cause the performance includes sprites)

**Comment by backspaces** [comment] 2015-04-10 16:43
Oh, and in terms of the inRadius/Cone, its a hybrid of agentsets having
inRect/Radius/Cone, and the individual agents using them for the NL
compliant interface.
